# Generated by Django 4.2.4 on 2023-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCC_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrent',
            name='firstname',
            field=models.CharField(blank=True, help_text='doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='concurrent',
            name='lastname',
            field=models.CharField(blank=True, help_text='john', max_length=100),
        ),
    ]
