# Generated by Django 4.2.4 on 2023-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCC_App', '0002_alter_concurrent_firstname_alter_concurrent_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrent',
            name='firstname',
            field=models.CharField(help_text='doe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='concurrent',
            name='lastname',
            field=models.CharField(help_text='john', max_length=100, null=True),
        ),
    ]
